---
abstract: 'command line pastebin'
author:
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  Dancer::Test: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::DBIx::Class: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300012, CPAN::Meta::Converter version 2.120900'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Hashbang-Pastebin
no_index:
  directory:
    - corpus
requires:
  DBIx::Class::Core: 0
  DBIx::Class::Schema: 0
  Dancer: 0
  Dancer::Plugin::DBIC: 0
  Dancer::Plugin::EscapeHTML: 0
  DateTime: 0
  DateTime::Format::MySQL: 0
  DateTime::Format::SQLite: 0
  Integer::Tiny: 0
  Plack: 0
  SQL::Translator: 0.11006
  Starman: 0
  Template: 0
  Try::Tiny: 0
  YAML: 0
  base: 0
  perl: 5.014000
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/doherty/WWW-Hashbang-Pastebin/issues
  homepage: http://metacpan.org/release/WWW-Hashbang-Pastebin/
  repository: git://github.com/doherty/WWW-Hashbang-Pastebin.git
version: 0.003
